package com.teamcs.database.bean;
// Generated 14 juin 2015 18:30:48 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Aeronef generated by hbm2java
 */
public class Aeronef  implements java.io.Serializable {


     private Integer idAeronef;
     private String libelleAeronef;
     private int poidsMax;
     private String dimensionPorte;
     private String dimensionCargo;
     private int volumeCargo;
     private int longueurPisteNecessaire;
     private int capacitePlein;
     private int capaciteVide;
     private int vitesse;
     private double consommation;
     private boolean disponibilite;
     private Set configurationaeronefs = new HashSet(0);
     private Set zonechargements = new HashSet(0);

    public Aeronef() {
    }

	
    public Aeronef(String libelleAeronef, int poidsMax, String dimensionPorte, String dimensionCargo, int volumeCargo, int longueurPisteNecessaire, int capacitePlein, int capaciteVide, int vitesse, double consommation, boolean disponibilite) {
        this.libelleAeronef = libelleAeronef;
        this.poidsMax = poidsMax;
        this.dimensionPorte = dimensionPorte;
        this.dimensionCargo = dimensionCargo;
        this.volumeCargo = volumeCargo;
        this.longueurPisteNecessaire = longueurPisteNecessaire;
        this.capacitePlein = capacitePlein;
        this.capaciteVide = capaciteVide;
        this.vitesse = vitesse;
        this.consommation = consommation;
        this.disponibilite = disponibilite;
    }
    public Aeronef(String libelleAeronef, int poidsMax, String dimensionPorte, String dimensionCargo, int volumeCargo, int longueurPisteNecessaire, int capacitePlein, int capaciteVide, int vitesse, double consommation, boolean disponibilite, Set configurationaeronefs, Set zonechargements) {
       this.libelleAeronef = libelleAeronef;
       this.poidsMax = poidsMax;
       this.dimensionPorte = dimensionPorte;
       this.dimensionCargo = dimensionCargo;
       this.volumeCargo = volumeCargo;
       this.longueurPisteNecessaire = longueurPisteNecessaire;
       this.capacitePlein = capacitePlein;
       this.capaciteVide = capaciteVide;
       this.vitesse = vitesse;
       this.consommation = consommation;
       this.disponibilite = disponibilite;
       this.configurationaeronefs = configurationaeronefs;
       this.zonechargements = zonechargements;
    }
   
    public Integer getIdAeronef() {
        return this.idAeronef;
    }
    
    public void setIdAeronef(Integer idAeronef) {
        this.idAeronef = idAeronef;
    }
    public String getLibelleAeronef() {
        return this.libelleAeronef;
    }
    
    public void setLibelleAeronef(String libelleAeronef) {
        this.libelleAeronef = libelleAeronef;
    }
    public int getPoidsMax() {
        return this.poidsMax;
    }
    
    public void setPoidsMax(int poidsMax) {
        this.poidsMax = poidsMax;
    }
    public String getDimensionPorte() {
        return this.dimensionPorte;
    }
    
    public void setDimensionPorte(String dimensionPorte) {
        this.dimensionPorte = dimensionPorte;
    }
    public String getDimensionCargo() {
        return this.dimensionCargo;
    }
    
    public void setDimensionCargo(String dimensionCargo) {
        this.dimensionCargo = dimensionCargo;
    }
    public int getVolumeCargo() {
        return this.volumeCargo;
    }
    
    public void setVolumeCargo(int volumeCargo) {
        this.volumeCargo = volumeCargo;
    }
    public int getLongueurPisteNecessaire() {
        return this.longueurPisteNecessaire;
    }
    
    public void setLongueurPisteNecessaire(int longueurPisteNecessaire) {
        this.longueurPisteNecessaire = longueurPisteNecessaire;
    }
    public int getCapacitePlein() {
        return this.capacitePlein;
    }
    
    public void setCapacitePlein(int capacitePlein) {
        this.capacitePlein = capacitePlein;
    }
    public int getCapaciteVide() {
        return this.capaciteVide;
    }
    
    public void setCapaciteVide(int capaciteVide) {
        this.capaciteVide = capaciteVide;
    }
    public int getVitesse() {
        return this.vitesse;
    }
    
    public void setVitesse(int vitesse) {
        this.vitesse = vitesse;
    }
    public double getConsommation() {
        return this.consommation;
    }
    
    public void setConsommation(double consommation) {
        this.consommation = consommation;
    }
    public boolean isDisponibilite() {
        return this.disponibilite;
    }
    
    public void setDisponibilite(boolean disponibilite) {
        this.disponibilite = disponibilite;
    }
    public Set getConfigurationaeronefs() {
        return this.configurationaeronefs;
    }
    
    public void setConfigurationaeronefs(Set configurationaeronefs) {
        this.configurationaeronefs = configurationaeronefs;
    }
    public Set getZonechargements() {
        return this.zonechargements;
    }
    
    public void setZonechargements(Set zonechargements) {
        this.zonechargements = zonechargements;
    }




}


