package com.teamcs.database.bean;
// Generated 8 juin 2015 21:32:57 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Classetherapeutique generated by hbm2java
 */
public class Classetherapeutique  implements java.io.Serializable {

    private Integer idClasseTherapeutique;
    private String libelleClasseTherapeutique;
    private Set medicaments = new HashSet(0);

    public Classetherapeutique() {
    }

    public Classetherapeutique(String libelleClasseTherapeutique) {
        this.libelleClasseTherapeutique = libelleClasseTherapeutique;
    }
    public Classetherapeutique(String libelleClasseTherapeutique, Set medicaments) {
       this.libelleClasseTherapeutique = libelleClasseTherapeutique;
       this.medicaments = medicaments;
    }
   
    public Integer getIdClasseTherapeutique() {
        return this.idClasseTherapeutique;
    }
    
    public void setIdClasseTherapeutique(Integer idClasseTherapeutique) {
        this.idClasseTherapeutique = idClasseTherapeutique;
    }
    public String getLibelleClasseTherapeutique() {
        return this.libelleClasseTherapeutique;
    }
    
    public void setLibelleClasseTherapeutique(String libelleClasseTherapeutique) {
        this.libelleClasseTherapeutique = libelleClasseTherapeutique;
    }
    public Set getMedicaments() {
        return this.medicaments;
    }
    
    public void setMedicaments(Set medicaments) {
        this.medicaments = medicaments;
    }
}


