package com.teamcs.database.bean;
// Generated 8 juin 2015 21:32:57 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Configurationaeronef generated by hbm2java
 */
public class Configurationaeronef  implements java.io.Serializable {

    private ConfigurationaeronefId id;
    private Aeronef aeronef;
    private Configuration configuration;
    private Date dateDepart;
    private Date dateRetour;

    public Configurationaeronef() {
    }

    public Configurationaeronef(ConfigurationaeronefId id, Aeronef aeronef, Configuration configuration, Date dateDepart, Date dateRetour) {
       this.id = id;
       this.aeronef = aeronef;
       this.configuration = configuration;
       this.dateDepart = dateDepart;
       this.dateRetour = dateRetour;
    }
   
    public ConfigurationaeronefId getId() {
        return this.id;
    }
    
    public void setId(ConfigurationaeronefId id) {
        this.id = id;
    }
    public Aeronef getAeronef() {
        return this.aeronef;
    }
    
    public void setAeronef(Aeronef aeronef) {
        this.aeronef = aeronef;
    }
    public Configuration getConfiguration() {
        return this.configuration;
    }
    
    public void setConfiguration(Configuration configuration) {
        this.configuration = configuration;
    }
    public Date getDateDepart() {
        return this.dateDepart;
    }
    
    public void setDateDepart(Date dateDepart) {
        this.dateDepart = dateDepart;
    }
    public Date getDateRetour() {
        return this.dateRetour;
    }
    
    public void setDateRetour(Date dateRetour) {
        this.dateRetour = dateRetour;
    }
}


