package com.teamcs.database.bean;
// Generated 8 juin 2015 21:32:57 by Hibernate Tools 4.3.1



/**
 * ConfigurationaeronefId generated by hbm2java
 */
public class ConfigurationaeronefId  implements java.io.Serializable {

    private int idConfiguration;
    private int idAeronef;

    public ConfigurationaeronefId() {
    }

    public ConfigurationaeronefId(int idConfiguration, int idAeronef) {
       this.idConfiguration = idConfiguration;
       this.idAeronef = idAeronef;
    }
   
    public int getIdConfiguration() {
        return this.idConfiguration;
    }
    
    public void setIdConfiguration(int idConfiguration) {
        this.idConfiguration = idConfiguration;
    }
    public int getIdAeronef() {
        return this.idAeronef;
    }
    
    public void setIdAeronef(int idAeronef) {
        this.idAeronef = idAeronef;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ConfigurationaeronefId) ) return false;
		 ConfigurationaeronefId castOther = ( ConfigurationaeronefId ) other; 
         
		 return (this.getIdConfiguration()==castOther.getIdConfiguration())
 && (this.getIdAeronef()==castOther.getIdAeronef());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdConfiguration();
         result = 37 * result + this.getIdAeronef();
         return result;
   }   
}


