package com.teamcs.database.bean;
// Generated 8 juin 2015 21:32:57 by Hibernate Tools 4.3.1



/**
 * Estcontenudans generated by hbm2java
 */
public class Estcontenudans  implements java.io.Serializable {

    private EstcontenudansId id;
    private Caisse caisse;
    private Contenu contenu;
    private int quantite;

    public Estcontenudans() {
    }

    public Estcontenudans(EstcontenudansId id, Caisse caisse, Contenu contenu, int quantite) {
       this.id = id;
       this.caisse = caisse;
       this.contenu = contenu;
       this.quantite = quantite;
    }
   
    public EstcontenudansId getId() {
        return this.id;
    }
    
    public void setId(EstcontenudansId id) {
        this.id = id;
    }
    public Caisse getCaisse() {
        return this.caisse;
    }
    
    public void setCaisse(Caisse caisse) {
        this.caisse = caisse;
    }
    public Contenu getContenu() {
        return this.contenu;
    }
    
    public void setContenu(Contenu contenu) {
        this.contenu = contenu;
    }
    public int getQuantite() {
        return this.quantite;
    }
    
    public void setQuantite(int quantite) {
        this.quantite = quantite;
    }
}


