package com.teamcs.database.bean;
// Generated 8 juin 2015 21:32:57 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Geolocalisation generated by hbm2java
 */
public class Geolocalisation  implements java.io.Serializable {

    private Integer idGeolocalisation;
    private double latitude;
    private double longitude;
    private Set caisses = new HashSet(0);

    public Geolocalisation() {
    }

    public Geolocalisation(double latitude, double longitude) {
        this.latitude = latitude;
        this.longitude = longitude;
    }
    public Geolocalisation(double latitude, double longitude, Set caisses) {
       this.latitude = latitude;
       this.longitude = longitude;
       this.caisses = caisses;
    }
   
    public Integer getIdGeolocalisation() {
        return this.idGeolocalisation;
    }
    
    public void setIdGeolocalisation(Integer idGeolocalisation) {
        this.idGeolocalisation = idGeolocalisation;
    }
    public double getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(double latitude) {
        this.latitude = latitude;
    }
    public double getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(double longitude) {
        this.longitude = longitude;
    }
    public Set getCaisses() {
        return this.caisses;
    }
    
    public void setCaisses(Set caisses) {
        this.caisses = caisses;
    }
}


