package com.teamcs.database.bean;
// Generated 14 juin 2015 18:30:48 by Hibernate Tools 4.3.1



/**
 * Materiel generated by hbm2java
 */
public class Materiel  implements java.io.Serializable {


     private Integer idMateriel;
     private String libelleMateriel;

    public Materiel() {
    }

    public Materiel(String libelleMateriel) {
       this.libelleMateriel = libelleMateriel;
    }
   
    public Integer getIdMateriel() {
        return this.idMateriel;
    }
    
    public void setIdMateriel(Integer idMateriel) {
        this.idMateriel = idMateriel;
    }
    public String getLibelleMateriel() {
        return this.libelleMateriel;
    }
    
    public void setLibelleMateriel(String libelleMateriel) {
        this.libelleMateriel = libelleMateriel;
    }




}


