package com.teamcs.database.bean;
// Generated 14 juin 2015 18:30:48 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Medicament generated by hbm2java
 */
public class Medicament  implements java.io.Serializable {


     private Integer idMedicament;
     private Classetherapeutique classetherapeutique;
     private int libelleMedicament;
     private Date dlu;
     private String dci;
     private String formeDosage;
     private int lot;
     private int dotationU7;

    public Medicament() {
    }

    public Medicament(Classetherapeutique classetherapeutique, int libelleMedicament, Date dlu, String dci, String formeDosage, int lot, int dotationU7) {
       this.classetherapeutique = classetherapeutique;
       this.libelleMedicament = libelleMedicament;
       this.dlu = dlu;
       this.dci = dci;
       this.formeDosage = formeDosage;
       this.lot = lot;
       this.dotationU7 = dotationU7;
    }
   
    public Integer getIdMedicament() {
        return this.idMedicament;
    }
    
    public void setIdMedicament(Integer idMedicament) {
        this.idMedicament = idMedicament;
    }
    public Classetherapeutique getClassetherapeutique() {
        return this.classetherapeutique;
    }
    
    public void setClassetherapeutique(Classetherapeutique classetherapeutique) {
        this.classetherapeutique = classetherapeutique;
    }
    public int getLibelleMedicament() {
        return this.libelleMedicament;
    }
    
    public void setLibelleMedicament(int libelleMedicament) {
        this.libelleMedicament = libelleMedicament;
    }
    public Date getDlu() {
        return this.dlu;
    }
    
    public void setDlu(Date dlu) {
        this.dlu = dlu;
    }
    public String getDci() {
        return this.dci;
    }
    
    public void setDci(String dci) {
        this.dci = dci;
    }
    public String getFormeDosage() {
        return this.formeDosage;
    }
    
    public void setFormeDosage(String formeDosage) {
        this.formeDosage = formeDosage;
    }
    public int getLot() {
        return this.lot;
    }
    
    public void setLot(int lot) {
        this.lot = lot;
    }
    public int getDotationU7() {
        return this.dotationU7;
    }
    
    public void setDotationU7(int dotationU7) {
        this.dotationU7 = dotationU7;
    }




}


