package com.teamcs.database.bean;
// Generated 14 juin 2015 18:30:48 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Observation generated by hbm2java
 */
public class Observation  implements java.io.Serializable {


     private Integer idObservation;
     private String libelleObservation;
     private Set caisses = new HashSet(0);

    public Observation() {
    }

	
    public Observation(String libelleObservation) {
        this.libelleObservation = libelleObservation;
    }
    public Observation(String libelleObservation, Set caisses) {
       this.libelleObservation = libelleObservation;
       this.caisses = caisses;
    }
   
    public Integer getIdObservation() {
        return this.idObservation;
    }
    
    public void setIdObservation(Integer idObservation) {
        this.idObservation = idObservation;
    }
    public String getLibelleObservation() {
        return this.libelleObservation;
    }
    
    public void setLibelleObservation(String libelleObservation) {
        this.libelleObservation = libelleObservation;
    }
    public Set getCaisses() {
        return this.caisses;
    }
    
    public void setCaisses(Set caisses) {
        this.caisses = caisses;
    }




}


