package com.teamcs.database.bean;
// Generated 14 juin 2015 18:30:48 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Statut generated by hbm2java
 */
public class Statut  implements java.io.Serializable {


     private Integer idStatut;
     private String libelleStatut;
     private Set utilisateurs = new HashSet(0);

    public Statut() {
    }

	
    public Statut(String libelleStatut) {
        this.libelleStatut = libelleStatut;
    }
    public Statut(String libelleStatut, Set utilisateurs) {
       this.libelleStatut = libelleStatut;
       this.utilisateurs = utilisateurs;
    }
   
    public Integer getIdStatut() {
        return this.idStatut;
    }
    
    public void setIdStatut(Integer idStatut) {
        this.idStatut = idStatut;
    }
    public String getLibelleStatut() {
        return this.libelleStatut;
    }
    
    public void setLibelleStatut(String libelleStatut) {
        this.libelleStatut = libelleStatut;
    }
    public Set getUtilisateurs() {
        return this.utilisateurs;
    }
    
    public void setUtilisateurs(Set utilisateurs) {
        this.utilisateurs = utilisateurs;
    }




}


