package com.teamcs.database.bean;
// Generated 14 juin 2015 18:30:48 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Typecaisse generated by hbm2java
 */
public class Typecaisse  implements java.io.Serializable {


     private Integer idTypeCaisse;
     private String libelleTypeCaisse;
     private Set caisses = new HashSet(0);

    public Typecaisse() {
    }

	
    public Typecaisse(String libelleTypeCaisse) {
        this.libelleTypeCaisse = libelleTypeCaisse;
    }
    public Typecaisse(String libelleTypeCaisse, Set caisses) {
       this.libelleTypeCaisse = libelleTypeCaisse;
       this.caisses = caisses;
    }
   
    public Integer getIdTypeCaisse() {
        return this.idTypeCaisse;
    }
    
    public void setIdTypeCaisse(Integer idTypeCaisse) {
        this.idTypeCaisse = idTypeCaisse;
    }
    public String getLibelleTypeCaisse() {
        return this.libelleTypeCaisse;
    }
    
    public void setLibelleTypeCaisse(String libelleTypeCaisse) {
        this.libelleTypeCaisse = libelleTypeCaisse;
    }
    public Set getCaisses() {
        return this.caisses;
    }
    
    public void setCaisses(Set caisses) {
        this.caisses = caisses;
    }




}


