package com.teamcs.database.bean;
// Generated 14 juin 2015 18:30:48 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;




/**
 * Utilisateur generated by hbm2java
 */
public class Utilisateur  implements java.io.Serializable {


     private String login;
     private Statut statut;
     private String nom;
     private String prenom;
     private String mail;
     private String rue;
     private String ville;
     private String codePostal;
     private String motDePasse;

    public Utilisateur() {
    }

    public Utilisateur(String login, Statut statut, String nom, String prenom, String mail, String rue, String ville, String codePostal, String motDePasse) {
       this.login = login;
       this.statut = statut;
       this.nom = nom;
       this.prenom = prenom;
       this.mail = mail;
       this.rue = rue;
       this.ville = ville;
       this.codePostal = codePostal;
       this.motDePasse = motDePasse;
    }
    
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public Statut getStatut() {
        return this.statut;
    }
    
    public void setStatut(Statut statut) {
        this.statut = statut;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }

    public String getRue() {
        return rue;
    }

    public void setRue(String rue) {
        this.rue = rue;
    }

    public String getVille() {
        return ville;
    }

    public void setVille(String ville) {
        this.ville = ville;
    }

    public String getCodePostal() {
        return codePostal;
    }

    public void setCodePostal(String codePostal) {
        this.codePostal = codePostal;
    }
    
    public String getMotDePasse() {
        return this.motDePasse;
    }
    
    public void setMotDePasse(String motDePasse) {
        this.motDePasse = motDePasse;
    }
}


