package com.teamcs.database.bean;
// Generated 14 juin 2015 18:30:48 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Zonechargement generated by hbm2java
 */
public class Zonechargement  implements java.io.Serializable {


     private Integer idZc;
     private String dimensionZc;
     private int volumeZc;
     private Set aeronefs = new HashSet(0);

    public Zonechargement() {
    }

	
    public Zonechargement(String dimensionZc, int volumeZc) {
        this.dimensionZc = dimensionZc;
        this.volumeZc = volumeZc;
    }
    public Zonechargement(String dimensionZc, int volumeZc, Set aeronefs) {
       this.dimensionZc = dimensionZc;
       this.volumeZc = volumeZc;
       this.aeronefs = aeronefs;
    }
   
    public Integer getIdZc() {
        return this.idZc;
    }
    
    public void setIdZc(Integer idZc) {
        this.idZc = idZc;
    }
    public String getDimensionZc() {
        return this.dimensionZc;
    }
    
    public void setDimensionZc(String dimensionZc) {
        this.dimensionZc = dimensionZc;
    }
    public int getVolumeZc() {
        return this.volumeZc;
    }
    
    public void setVolumeZc(int volumeZc) {
        this.volumeZc = volumeZc;
    }
    public Set getAeronefs() {
        return this.aeronefs;
    }
    
    public void setAeronefs(Set aeronefs) {
        this.aeronefs = aeronefs;
    }




}


